### ISSUE TITLE
JOSS Publication Checklist 

### ISSUE THREAD

**Issue by nniiicc** [CouncilDataProject/cdptools#151]
Re-starting work on the JOSS paper... Tagging appropriate people responsible for the sections of the paper

- [x] A list of the authors of the software and their affiliations, using the correct format (see the example below).
- [ ] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience. @JacksonMaxfield 
- [ ] A clear Statement of Need that illustrates the research purpose of the software. @nniiicc @JacksonMaxfield (to double check)
- [ ] A list of key references, including to other software addressing related needs. @nniiicc @JacksonMaxfield 
- [ ] Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it. @nniiicc 
- [ ] Acknowledgement of any financial support. (NA)

https://joss.readthedocs.io/en/latest/submitting.html
